### ISSUE TITLE
Photo gallery component loads with no styling in the carousel on a first load from a fresh bundle.

### ISSUE THREAD

**Issue by manuelreneduran** [rpt14-codeblooded/photo-gallery-service#45]

**Comment by manuelreneduran** [comment]
@creationator just a heads up, you might run into this. From my own investigations it seems that styled components doesn't like that both of our services are using it at the same time.

This is the warning I'm getting:
![image](https://user-images.githubusercontent.com/44199224/60631233-1ef47980-9dc4-11e9-9dd4-83afefa07aef.png)

What's happening is that when you first load the page just after creating a bundle, my service will have no styling on the carousel, leaving it looking like this:

![image](https://user-images.githubusercontent.com/44199224/60631269-59f6ad00-9dc4-11e9-8bbc-aa22c318e3ea.png)

However, if you reload everything looks and works fine. 

I'm going to continue investigating.

**Comment by hegitsit** [comment]
Hmmm this is interesting. I hope that it isn't the case where styled components don't play nice when being loaded from two different services.

**Comment by manuelreneduran** [comment]
I managed to solve the problem but I'm not proud of the solution. I installed a previous version of styled components in my service and kept yours the same. You still get the collision error but everything works fine. I'm going to push up my latest code so that hopefully you don't have to deal with the same error.
